function latin2arab(latinturkishStr) {
    const arabicText0 = latinturkishStr+' '
    
    ;
    const arabicText1 = arabicText0
    .replace(/ A/g, ' آ')
    .replace(/ a/g, ' ا')
    .replace(/ O/g, ' او')
    .replace(/ o/g, ' او')
    .replace(/ U/g, ' او')
    .replace(/ u/g, ' او')
    .replace(/ I/g, ' اؽ')
    .replace(/ ı/g, ' اؽ')
    .replace(/ Ə/g, ' ا')
    .replace(/ ə/g, ' ا')
    .replace(/ E/g, ' ائ')
    .replace(/ e/g, ' ائ')
    .replace(/ Ö/g, ' اؤ')
    .replace(/ ö/g, ' اؤ')
    .replace(/ Ü/g, ' اۆ')
    .replace(/ ü/g, ' اۆ')
    .replace(/ İ/g, ' ای')
    .replace(/ i/g, ' ای')
    .replace(/Ə /g, 'ه ')
    .replace(/ə /g, 'ه ')
    ;
    const arabicText2 = arabicText1
    .replace(/a/g, 'ا')
    .replace(/b/g, 'ب')
    .replace(/c/g, 'ج')
    .replace(/ç/g, 'چ')
    .replace(/d/g, 'د')
    .replace(/e/g, 'ئ')
    .replace(/ə/g, 'َ')
    .replace(/f/g, 'ف')
    .replace(/g/g, 'گ')
    .replace(/ğ/g, 'غ')
    .replace(/h/g, 'ح')
    .replace(/ı/g, 'ؽ')
    .replace(/i/g, 'ی')
    .replace(/j/g, 'ژ')
    .replace(/k/g, 'ک')
    .replace(/l/g, 'ل')
    .replace(/m/g, 'م')
    .replace(/n/g, 'ن')
    .replace(/ñ/g, 'ڭ')
    .replace(/o/g, 'و')
    .replace(/ö/g, 'ؤ')
    .replace(/p/g, 'پ')
    .replace(/q/g, 'ق')
    .replace(/r/g, 'ر')
    .replace(/s/g, 'س')
    .replace(/ş/g, 'ش')
    .replace(/t/g, 'ت')
    .replace(/u/g, 'و')
    .replace(/ü/g, 'ۆ')
    .replace(/v/g, 'و')
    .replace(/w/g, 'و')
    .replace(/y/g, 'ی')
    .replace(/z/g, 'ز')
    .replace(/x/g, 'خ')
    .replace(/A/g, 'ا')
    .replace(/B/g, 'ب')
    .replace(/C/g, 'ج')
    .replace(/Ç/g, 'چ')
    .replace(/D/g, 'د')
    .replace(/E/g, 'ئ')
    .replace(/Ə/g, 'َ')
    .replace(/F/g, 'ف')
    .replace(/G/g, 'گ')
    .replace(/Ğ/g, 'غ')
    .replace(/H/g, 'ح')
    .replace(/I/g, 'ؽ')
    .replace(/İ/g, 'ی')
    .replace(/J/g, 'ژ')
    .replace(/K/g, 'ک')
    .replace(/L/g, 'ل')
    .replace(/M/g, 'م')
    .replace(/N/g, 'ن')
    .replace(/Ñ/g, 'ڭ')
    .replace(/O/g, 'و')
    .replace(/Ö/g, 'ؤ')
    .replace(/P/g, 'پ')
    .replace(/Q/g, 'ق')
    .replace(/R/g, 'ر')
    .replace(/S/g, 'س')
    .replace(/Ş/g, 'ش')
    .replace(/T/g, 'ت')
    .replace(/U/g, 'و')
    .replace(/Ü/g, 'ۆ')
    .replace(/V/g, 'و')
    .replace(/W/g, 'و')
    .replace(/Y/g, 'ی')
    .replace(/Z/g, 'ز')
    .replace(/X/g, 'خ')
    ;



    


    return arabicText2;
}