function ozbekcha2ozbekce(ozbekchaStr) {
   const ozbekchaText0 =ozbekchaStr
   .replace(/o’/g, 'o‘')
   .replace(/O’/g, 'O‘')
   .replace(/oʻ/g, 'o‘')
   .replace(/Oʻ/g, 'O‘')

   .replace(/gʻ/g, 'g‘')
   .replace(/Gʻ/g, 'G‘')
   .replace(/g’/g, 'g‘')
   .replace(/G’/g, 'G‘')
   .replace(/kino/g, 'kino‘')
   .replace(/doktor/g, 'do‘kto‘r')
   .replace(/morfolo/g, 'mo‘rfo‘lo‘')
   ;
/*
АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЪъЬьЭэЮюЯяЎўҒғҚқҲҳ
*/
   const ozbekceText1 = ozbekchaText0
   .replace(/А/g, 'A')
   .replace(/а/g, 'a')
   .replace(/Б/g, 'B')
   .replace(/б/g, 'b')
   .replace(/В/g, 'V')
   .replace(/в/g, 'v')
   .replace(/Г/g, 'G')
   .replace(/г/g, 'g')
   .replace(/Д/g, 'D')
   .replace(/д/g, 'd')
   .replace(/Е/g, 'E')
   .replace(/е/g, 'e')
   .replace(/Ё/g, 'Yo')
   .replace(/ё/g, 'yo')
   .replace(/Ж/g, 'J')
   .replace(/ж/g, 'j')
   .replace(/З/g, 'Z')
   .replace(/з/g, 'z')
   .replace(/И/g, 'İ')
   .replace(/и/g, 'i')
   .replace(/Й/g, 'Y')
   .replace(/й/g, 'y')
   .replace(/К/g, 'K')
   .replace(/к/g, 'k')
   .replace(/Л/g, 'L')
   .replace(/л/g, 'l')
   .replace(/М/g, 'M')
   .replace(/м/g, 'm')
   .replace(/Н/g, 'N')
   .replace(/н/g, 'n')
   .replace(/О/g, 'O')
   .replace(/о/g, 'o')
   .replace(/П/g, 'P')
   .replace(/п/g, 'p')
   .replace(/Р/g, 'R')
   .replace(/р/g, 'r')
   .replace(/С/g, 'S')
   .replace(/с/g, 's')
   .replace(/Т/g, 'T')
   .replace(/т/g, 't')
   .replace(/У/g, 'U')
   .replace(/у/g, 'u')
   .replace(/Ф/g, 'F')
   .replace(/ф/g, 'f')
   .replace(/Х/g, 'X')
   .replace(/х/g, 'x')
   .replace(/Ц/g, 'TS')
   .replace(/ц/g, 'ts')
   .replace(/Ч/g, 'Ch')
   .replace(/ч/g, 'ch')
   .replace(/Ш/g, 'Sh')
   .replace(/ш/g, 'sh')
   .replace(/Ъ/g, 'ʼ')
   .replace(/ъ/g, 'ʼ')
   .replace(/Ь/g, 'ʼ')
   .replace(/ь/g, 'ʼ')
   .replace(/Э/g, 'E')
   .replace(/э/g, 'e')
   .replace(/Ю/g, 'Yu')
   .replace(/ю/g, 'yu')
   .replace(/Я/g, 'Ya')
   .replace(/я/g, 'ya')
   .replace(/Ў/g, 'O‘')
   .replace(/ў/g, 'o‘')
   .replace(/Ғ/g, 'G‘')
   .replace(/ғ/g, 'g‘')
   .replace(/Қ/g, 'Q')
   .replace(/қ/g, 'q')
   .replace(/Ҳ/g, 'H')
   .replace(/ҳ/g, 'h')
   ;

    const ozbekceText2 = ozbekceText1
    .replace(/a/g, 'ə')
    .replace(/A/g, 'Ə')
    .replace(/j/g, 'c')
    .replace(/J/g, 'C')
    .replace(/CH/g, 'Ç')
    .replace(/Ch/g, 'ç')
    .replace(/ch/g, 'ç')
    .replace(/SH/g, 'Ş')
    .replace(/Sh/g, 'Ş')    
    .replace(/sh/g, 'ş')
    .replace(/NG/g, 'Ñ')
    .replace(/Ng/g, 'Ñ')    
    .replace(/ng/g, 'ñ')
    .replace(/G‘/g, 'Ğ')
    .replace(/g‘/g, 'ğ')    
    .replace(/O‘/g, 'Ō')    
    .replace(/o‘/g, 'ō')
    .replace(/o/g, 'a')
    .replace(/O/g, 'A')
				.replace(/I/g, 'İ')
    ;


    const ozbekceText3 = ozbekceText2
    .replace(/Сентябр/g, 'Sentabr')
    .replace(/Октябр/g, 'Oktabr')
    
    ;

    return ozbekceText3;
}